### PR TITLE
Add Curve base class to all non-linear curves.

### PR DESCRIPTION
**Pull request by udifuchs**
Also export module symbols Curve and Linear.

In my code, I need to know if a path element is Linear or a Curve. With this change, my use of svg.path would be more elegant.

### CODE REVIEW

**Comment by tatarize** [comment]
Hm. There was some movement towards having a `Linear` based added to the PathSegments in `svgelements` in part to parallel the code here, but I do like the elegance of the taxonomy here.

**Comment by regebro** [comment]
I'm wondering if we should make those classes abstract?

**Comment by tatarize** [comment]
There isn't that much code overlap. In fact, as best as I can tell, there's none with Curve, if you also have a PathSegment.

My Curve class in svgelements just calls parent and sets the value of start and end. PathSegment implements `relative` and `smooth`, `__mult__` by a matrix. `__iadd__` with another PathSegment or a string (path_d fragment), `__str__` to do segment path_d strings. The `__iter__` and `__next__` Has the `segment_length` code to do the recursive approximations of length by straight lines, `bbox` which needs to be overloaded in some of the individual Path Segment. `reverse` which flips the individual path segment. `point` for finding a particular point. `npoint` for finding np.array() of points since in production code that's actually highly important (without the requirement, the code just doesn't work without numpy). `length` which defers to the various length codes and fall backs, and 'd' which gives the individual fragment path_d code there.

Not that Curve is a bad idea, but literally there's no code shared there at all. I could almost see Bezier being a class that would maybe descend from Curve if you went all out with hierarchies, at least then you could have a non-abstract Bezier curve which could implement N-point Bezier and just have simplifications of that code within Quad and Cubic. Mathandy has some nice tools that refer to n-point Bezier curves but don't really apply to any of the defined SVG PathSegments. ( https://github.com/mathandy/svgpathtools/blob/master/svgpathtools/bezier.py ).

I have plans for another svg module that sort of uses a lot more stuff from `svgwrite` and `svgpathtools` and `svgelements` and `svg.path`. I could absolutely see having Curve and Bezier, especially if Bezier would not be strictly abstract, and serve as a home for other objects. 

I like the hierarchy and doubt it costs much but there's not really much that matters within a very general `Curve`, other than giving a home to to some future functions or changes. Beziers have a lot in common, and certainly give a home to n-degree curves. And there are some functions that are nice to predefine or give solid fallbacks to in a PathSegment class.  In fact most of the stuff you put in Linear, ended up in PathSegment in svgelements. And it gives a more proper home to segment_length() as a function.

**Comment by vidstige** [comment]
This seems very reasonable

**Comment by regebro** [comment]
OK, I added some abstract base classes. Opinions on those?

**Comment by vidstige** [comment]
> OK, I added some abstract base classes. Opinions on those?

Looks great!

**Comment by tatarize** [comment]
NonLinear seems a bit negative. I know there's NonLinear geometry or whatever but you're defining a class by what it's not. I mean it's not exactly NonRabbit but it's also not a rabbit. Also, some degenerate values within the SVG spec of things like arcs that violate some criteria that they must be long enough to reach the endpoint actually *are* linear since defaulting to line is the base case.

**Comment by vidstige** [comment]
Your arguments makes sense. To me non-linear is a term in itself, much like like "incorrect" or "inconsistent" but I see that it can seem like a negative definition to others. Also the Linear and NonLinear base-classes are mutually exclusive so that also makes it more sensible to keep the name. Do you have some alternativ name you want to suggest?

**Pull request closed without merging**
