### PR TITLE
Path/Parser Integration

### PR DESCRIPTION
**Pull request by tatarize**
The path and parser are the two main files used by `svg.path` however, these two are intimately linked, but still stored separately.  The utility and usability of this goes up significantly if we are permitted to define paths with contexts like `Path('M0,0v50h50v-50z')`.

* Test coverage is added to prove the parser code and Path(path_d, current_pos) is identical
* All original tests still pass.
* No breaking changes.

With this change, only `path.py` is needed. The `parser.py` is reduced to a stub for legacy reasons. Users would only need a copy of `path.py` without the `parser.py` for full functionality, and this would also allow them to easily correct the import problems they will commonly have using this library.

Defining a path by using the Path's constructor is much more intuitive.

### CODE REVIEW

**Comment by regebro** [comment]
They are only intricately linked in as much as parser imports path because it generates Path objects in the end.

I really don't see how this improves anything.

**Comment by tatarize** [comment]
It's helpful when you're using the Path objects since you can just do `Path("M0,0z")` etc. Makes the syntax much easier and you don't need to know the parser or remember to import it or anything. If you have Path objects you can just pass them a pathd string directly. It would seem like you're reducing two lines to one, but really you're also making the Path class itself the only class you actually need.

I could see the argument that this is too much coupling or something but the parser only does Path objects and you can't really do anything with the parser alone. They are really far better as a single class so you don't need a weird secondary function to initialize your Path objects, you can just call the `__init__` function of the Path object. 

If you know your SVG, it's *much* easier to write path_d code than string together a bunch of PathSegments. Try looking at any code you've written with your module and then consider how much cleaner it looks with this change. It also give path_d a sort of middle language since things are easier to parse than to load up any of the pathsegments yourself. Basically defining any Path you'd never really care to import those pathsegments anymore since you'd get them all loading internally in Path when you parse things.

**Comment by regebro** [comment]
Sure, you can just do `Path("M0,0z")`, but you can also just do `parse_path("M0,0z")`. It's literally just 6 characters more.

The reason I didn't do `Path("M0,0z")` is because Path() is a MutableSequence. We can overload `__init__ `so that if it gets only one string argument, it parses the path. But I'm not particularly fond of overloading. And we DO need a way to create a Path from Segments, because we want to be able to test the Path objects in a way that is separated from parsing.

We can also move the parsing to a @staticmethod, so you do `Path.from_string("M0,0z")` or maybe `Path.parse("M0,0z")`.  But none of these actually bring any actual benefits.

In addition the  path.py  is long enough and has enough classes to be hard to navigate already, so I don't want to make it larger for no reason.  So I'll keep them separate.

**Comment by tatarize** [comment]
Heh. In `svgelements` the `Arc` code is longer than the *entire* codebase of svg.path. Though it covers every parameterization of arc mathematically possible down to sagatta and control points.

**Pull request closed without merging**
