### PR TITLE
arc.length

### PR DESCRIPTION
**Pull request by tatarize**
Tweaks arc.length() to numerically integrate.

### CODE REVIEW

**Comment by regebro** [comment]
Oh, nice, that's a lot better than I expected when I looked at the maths.  I'll try to get a better look at it before merging, but since tests pass...

**Comment by tatarize** [comment]
I ran a few tests and it's basically instant in comparison. It gets worse answers than the line-based methods with large eccentricities.  Do note, your coverage here isn't as strong as you'd think since most of them will actually do the circle fallback. In fact, I think all of the arcs actually do. I think I initially had a sign flip and it *still* passed the tests.

Asked the question to StackOverflow and it got a solid answer a day or so ago. And just noticed.

https://stackoverflow.com/questions/58650448/calculating-the-exact-length-of-an-svg-arc-in-python

The references there are actually fantastic, and I might actually want to implement a version that uses the fancy scipy function for testing purposes.  As is, I had to use circle arcs while avoiding the circle shortcuts and also tested it with almost-full-circle arcs against a scipy exact answer calculation using the required hypergeometric function.

**Comment by tatarize** [comment]
```
from __future__ import division

import unittest
from math import sqrt, radians, sin
from random import random

from ..path import Arc, segment_length

from scipy import pi, sqrt
from scipy.special import hyp2f1


def exact_ellipse_circumference(arc):
    r = arc.radius * arc.radius_scale
    a = r.real
    b = r.imag
    t = ((a - b) / (a + b)) ** 2
    return pi * (a + b) * hyp2f1(-0.5, -0.5, 1, t)


def integrated_arc_len(arc):
    def ellipse_part_integral(t1, t2, a, b, n=100):
        # function to integrate
        def f(t):
            return sqrt(1 - (1 - a ** 2 / b ** 2) * sin(t) ** 2)

        start = min(t1, t2)
        seg_len = abs(t1 - t2) / n
        return b * sum(f(start + seg_len * (i + 1)) * seg_len for i in range(n))

    r = arc.radius * arc.radius_scale
    return ellipse_part_integral(radians(arc.theta), radians(arc.theta + arc.delta), r.real, r.imag)


def circle_arc_len(arc):
    radius = arc.radius.real * arc.radius_scale
    return abs(radius * radians(arc.delta))


class TestArcLengths(unittest.TestCase):

    def test_arc_length_circle2(self):
        def get_random_circle_arc():
            radius = random() * 50 + random() * 50 * 1j
            start = random() * 50 + (random() * 50) * 1j
            return Arc(start, radius, 180 * random(), 1, 0, start+1e-14)

        for i in range(1000):
            arc = get_random_circle_arc()
            start_point = arc.point(0)
            end_point = arc.point(1)
            length_calc = exact_ellipse_circumference(arc)
            length_int = integrated_arc_len(arc)
            length_seg = segment_length(arc, 0, 1, start_point, end_point, 1e-10, 5, 0)
            print("%.15f == %.15f, dif: %.15f\n%.15f == %.15f, dif: %.15f\n %s" % (
            length_calc, length_seg, length_calc - length_seg,
            length_calc, length_int, length_calc - length_int,
            str(arc)))
            self.assertAlmostEqual(length_int, length_calc, places=1)
```

170.448700284897370 == 170.448700135767240, dif: 0.000000149130130
170.448700284897370 == 170.448705208412520, dif: -0.000004923515149
 Arc(start=(36.893320302883005+3.1018532813250066j), radius=(3.9568374149861807+42.00508028534738j), rotation=167.69597158864994, arc=True, sweep=False, end=(36.89332030288301+3.1018532813250066j))
153.285854811793541 == 153.285854615014898, dif: 0.000000196778643
153.285854811793541 == 153.285854811793541, dif: 0.000000000000000
 Arc(start=(24.409850080480666+44.71732218076815j), radius=(34.33444558573292+11.598473329056452j), rotation=155.70068193225504, arc=True, sweep=False, end=(24.409850080480677+44.71732218076815j))

When the ratio of one radius dwarfs the other radius the numbers don't perform as well. It might actually be the subdivision until the difference is above the given threshold. That might well do high curvature elements really well. Though obviously adding a zero or two to the n value could also work.

**Comment by tatarize** [comment]
77.461874470828050 == 77.461874460486428, dif: 0.000000010341623
77.461874470828050 == 77.461751699543868, dif: 0.000122771284182

 Arc(start=(19.886526697032508+42.45830547396991j), radius=(19.365414684490545+0.016185817912622857j), rotation=91.58488052161456, arc=True, sweep=False, end=(19.88652669703252+42.45830547396991j))

The eccentricity here is is 19.4 / 0.016 and it's off by almost 1e-3 that's as extreme as that error gets though. The other method is pretty consistently worse but does outperform in those cases when it's kinda more line-like already.

**Comment by tatarize** [comment]
My current understanding is that typically it will instantly give you the right answer with error around 1e-10 for 99.998% of arcs. But, for a couple with sharp points the error can spike to almost 1e-3. I'm working on trying to get the exact formula to work to test it against. Requires scipy.special.ellipeinc. 

Though it doesn't yet work, would you reasonably want code that tried to use such a function?

```
    def _exact_arc_length(self):
        try:
            from scipy.special import ellipeinc
        except ImportError:
            return self._arc_length()
        angle = self.theta
        a = self.rx
        b = self.ry
        phi = atan(a/b * tan(angle))
        m = 1 - (a/b) ** 2
        d1 = ellipeinc(phi, m)
        angle = self.theta + self.sweep
        phi = atan(a / b * tan(angle))
        m = 1 - (a / b) ** 2
        d2 = ellipeinc(phi, m)
        return b * abs(d2 - d1)
```

It wouldn't require scipy.special as a dependency but *if* that code happens to exist, it could use the hypergeometric function to solve the length exactly. But, if trying to import it causes an import error then it defers to one of the other arc length functions. There's a list of potential objections to this, it will change the answer depending on what modules are installed, it's still a quasi dependency, etc. Assuming I get it working and can actually use it to perform tests of the other function.

**Comment by tatarize** [comment]
Also, some of your error spikes pretty hard at pancaked arcs too. So I'm not that worried. You'd think this test, would produce nothing. But, it starts tossing out pancaked arcs like like they are candy.

```
    def test_arc_theta(self):
        def get_random_arc():
            radius = random() * 50 + (random() * 50) * 1j
            start = random() * 50 + (random() * 50) * 1j
            end = random() * 50 + (random() * 50) * 1j
            return Arc(start, radius, int(random() * 180), int(random() * 2), int(random() * 2), end)

        for i in range(1000000):
            arc = get_random_arc()
            d1 = arc.start - arc.point(0)
            d2 = arc.end - arc.point(1)
            if abs(d1) > 1e-3:
                print(repr(arc))
            if abs(d2) > 1e-3:
                print(repr(arc))
```

**Comment by regebro** [comment]
At that eccentricity it's basically a line, so. :-)

**Comment by tatarize** [comment]
I got exact working in some of my code. And comparing it with integral and lines methods finds that lines while it take a bit of a speed hit, is actually a lot more accurate. Upping the n-value seems to narrow it down but getting the same resolution seems like it would take longer. While the cursory look with circles had it getting better answers faster, arbitrary arcs seem like they underperform. 

I'll do a bit more research. Maybe there's something causing an error in the integral code that just reduces the error with the segment length or something along those lines. The exact solution with scipy's function is instantaneous. And a try, except, import might be reasonable.

**Comment by tatarize** [comment]
I'll close this for now. It doesn't outperform the current method. And readd it if some tweaks makes it do so. Comparing with exact let me better gauge the performance.

**Pull request closed without merging**
