### PR TITLE
Tangent

### PR DESCRIPTION
**Pull request by vidstige**
Adds support for computing ~derivative~ tangent of a Path (or individual segments) at a specific parameterised point. Also added relevant test case.

~Arc support is currently lacking, but~ this is very helpful for myself at least and I thought I'd share it for others.

### CODE REVIEW

**Comment by regebro** [comment]
OK, interesting, what is the usecase for this? Is not part of SVG as far as I can tell?

**Comment by vidstige** [comment]
Thanks for a fast review. It's not part of svg per se, nor is `point()`, but it's very handy if you want to do things with it paths. The same goes for `derivative()` although the use case is more narrow. Due to it's nature, it turned out very ugly to implement outside of this library.

Use-cases
* Draw arrow heads at end of paths and more
* Things like these (that's what I sometimes play around with)
smoke
rubber

**Comment by regebro** [comment]
Well, `point()` is the basic function of the whole library, without it it would be useless, as you couldn't draw the line. :-D

Since this is technically a transformation, it could fit together with SVG transforms in an svg.transforms library? I think there should be one, but of course nobody has had the time to make it. :-)

But then again, the reason for making the SVG transforms separate is that they apply to different things that paths. How would derivatives look on things other SVG shapes, like cubes on ellipses?

**Comment by vidstige** [comment]
Well, this computes the derivative (direction) at a specific point. Much like the `point()` function. It's not really a transformation, it just computes a value at a specific parameterised point (0-1) much like `point()`. It's an inherent property of the un-transformed svg path. All curves has a position and direction at each point, so it would be very similar for cubes on ellipses. 

It could be in it's own library, but it would then be convenient to depend on _this_ library for parsing and the segment types, etc. However, then it would be nice to have some more things exposed from this library. Like the `_find_segment()` in this PR. Basically, expose enough things so that `point()` can be implemented in a imaginary "svg.transforms" library.

If I understand you correctly and read a bit between the lines, you would like this to be svg parsing + point() function and nothing more to keep it minimalist? Just trying to understand.

**Comment by regebro** [comment]
Could you implement it for `Arc` as well? The more I think about it, the more it seems to make sense. 

Come to think of it, I'm not sure derivative is the best name, even though that's what it is mathematically. What would the result be at a hard 90 degree corner, for example?

**Comment by vidstige** [comment]
Yes, I'll add the `Arc` as well then.

Yes, it's not really defined at a 90 degree corner (or any corner), but as I implemented it will just follow the current segment, e.g. a the corners of a square would have the direction of the first segment at e.g. t=0.

Other names include "tangent" or "direction". What do you think about any of these? There is also the related concept of "normal" where the tangent is multiplied with _i_ (rotated)

**Comment by regebro** [comment]
I like "tangent".

I guess the path function could take the average of the end tangent for one segment and the start tangent for the other, when you enter exactly that point? Does that make sense?

**Comment by vidstige** [comment]
Let's go for "tangent"! :ok_hand: 

I don't think it would make sense to return the average. It's really not defined, so I think either as it is now, or return `None` would make most sense. As it is now is probably the easiest to use, if you e.g. loop over short curve segments and draw the tangent, it would average "by itself".

**Comment by regebro** [comment]
Yeah, that's better than None, in any case.

**Comment by vidstige** [comment]
The lengths (`abs()`) of the tangents are a bit arbitrary right now. They should probably be divided by the total length of the segment to make more sense. Or normalized to 1

**Comment by vidstige** [comment]
@regebro what do you think about the current branch? What is needed to merge? Do you think this belongs in this library at all?

**Comment by regebro** [comment]
I would like to look a bit more at it, but I do think it belongs-

**Comment by regebro** [comment]
OK, sorry, I got distracted, mainly by a war. This is basically me thinking out loud:

Now, looking at this, I see that for example, for a line it returns end-start. That means the result you get is a vector, which makes sense. For example, for a line starting at 1+3j and ending ad 3+9j, essentially a `y=3x` line, the derivative would be 3, and that's definitely not what's returned, so the change to `tangent()` is good. However, as it's a tangent, I wonder if it shouldn't be normalized? It doesn't really have a magnitude, just a direction. 

On the other hand, I guess you could see the length of the line as a sort of magnitude, and that would then be reflected in the vector in that case. Would that be reflected also in other tangents? I think it would, but I'm not 100% sure.

**Comment by regebro** [comment]
I did some tests on this, and it checks out.

**Comment by regebro** [comment]
Awesome job, thanks.

**Comment by vidstige** [comment]
🎉 nice! :-) 

Regarding the magnitude, I was in the same train of thought. The magnitude would make sense of of it's the "speed" of the curve at that point. But I thought about it (but did not do any calculations) and it seemed to me the "speed" would be constant. It works the same for the arc, e.g. the larger the arc the bigger the magnitude. I didn't check it for the bezier, but it should be the same. Here I wasn't sure if the "speed" was constant. All things considered, this was what I thought made most sense as it's most "raw".

Regarding the name - "Derivative" _does_ make sense, but only if you consider the path a function of the parameter `t`, but not if you consider y a function of x or vice versa. Then the partial derivatives dx/td and dy/dt works out to be a vector and this is what is returned. But "tangent" is just as good a name, if not better. I like it.

**Comment by vidstige** [comment]
I did this for Valentines Day with the help of your nice library

https://twitter.com/i/status/1493173657698512897

**Comment by regebro** [comment]
So I added a graphical test, and the magnitude over bezier curves are not constant, it's larger is the line is straighter, I think, which I guess makes sense. But more importantly it does increase with the length of the curve. 

Nice image!

**Pull request merged**
