### PR TITLE
Import ABC from collections.abc instead of collections for Python 3.9 compatibility

### LINKED ISSUE #56: Importing ABC directly from collections module was removed in Python 3.9
https://bugzilla.redhat.com/show_bug.cgi?id=1793023

https://github.com/regebro/svg.path/blob/1feb211225aab7f215203475b94b2569ca9d025b/src/svg/path/path.py#L3

Thanks for the library!

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #56

### CODE REVIEW

**Comment by regebro** [comment]
Thanks. Can you also update the CHANGES.txt and add yourself to the contributors list? Then I can just merge it.

**Comment by regebro** [comment]
Oups, wrong button.

**Comment by tirkarthi** [comment]
@regebro Added, please let me know if I need to change something. Thanks.

**Comment by dcambie** [comment]
Hi!

Thanks
I was wondering if is there a timeline to release a version including this PR?

**Comment by regebro** [comment]
Oups. Released.

**Pull request merged**
