### PR TITLE
test_doc.py: don't use relative path to import doctests

### PR DESCRIPTION
**Pull request by danstender**
Hi,

we've applied this patch for Debian packaging (Debian package is coming up).

Best,
Daniel Stender

### CODE REVIEW

**Comment by regebro** [comment]
Thanks, that's what happens when you are lazy, and then forgot to fix the quick hack. :-)

**Comment by danstender** [comment]
The cologne dome is also never finished ;-)

BTW, Python-svg.path and Hovercraft Debian packages are around the corner.

Cheers,
DS


-- 
4096R/DF5182C8
46CB 1CA8 9EA3 B743 7676 1DB9 15E0 9AF4 DF51 82C8
LPI certified Linux admin (LPI000329859 64mz6f7kt4)
http://www.danielstender.com/blog/

**Comment by regebro** [comment]
Awesome! I need to learn how to package on RedHat OS's for this (and Hovercraft!)

**Comment by danstender** [comment]
Maybe they'll pick it up, too. The best for that!

Greetings,
DS

**Pull request merged**
